version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = [
    "Dockerfile",
    "docker-compose.yml"
]

[[analyzers]]
name = "java"

[analyzers.meta]
runtime_version = "17"