stages:
  - test
  - build-artifact
  - build-image
  - post-test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

maven-build:
  stage: build-artifact
  image: docker.io/library/maven:3-amazoncorretto-19
  script:
    - mvn package
  artifacts:
    name: "andorvini-dingus-player-maven_package-full_jar-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID"
    paths:
      - target/*-spring-boot.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_MESSAGE =~ /\[ci\]/
      when: manual

docker-image-build:
  stage: build-image
  image: docker.io/library/docker:20-git
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE/bot:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image push --all-tags $CI_REGISTRY_IMAGE/bot
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_MESSAGE =~ /\[ci\]/
      when: manual

container_scanning:
  stage: post-test
  variables:
    CS_DISABLE_DEPENDENCY_LIST: "true"
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE/bot:latest
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/bot
    CI_APPLICATION_TAG: "latest"
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"
    CS_ANALYZER_IMAGE: "registry.gitlab.com/security-products/container-scanning/grype:5"
    SECURE_LOG_LEVEL: "debug"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_MESSAGE =~ /\[ci\]/
      when: manual
