stages:
  - build-artifact
  - build-image
  - deploy

maven-build:
  stage: build-artifact
  image: docker.io/library/maven:3-amazoncorretto-21
  script:
    - mvn package
  artifacts:
    name: "andorvini-discord-dingus-player-maven_package-full_jar-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID"
    paths:
      - target/*-spring-boot.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

docker-image-build:
  needs:
    - maven-build
  dependencies:
    - maven-build
  stage: build-image
  image: docker.io/library/docker:git
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE/bot:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image push --all-tags $CI_REGISTRY_IMAGE/bot
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

portainer-trigger:
  needs:
    - docker-image-build
  dependencies:
    - docker-image-build
  when: on_success
  stage: deploy
  image: docker.io/library/alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - curl -f -X POST $PORTAINER_WEBHOOK
